version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 4gb     # set shared memory limit when using docker-compose
    environment:
      POSTGRES_PASSWORD: alaffia
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

